# config/_default/menus.zh-Hans.toml

[[main]]
  name = "博客"
  pageRef = "post"
  weight = 10

[[main]]
  name = "AI相关"
  pageRef = "AI"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/3377"
  weight = 30
  [main.params]
    icon = "github"
    showName = true
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "隐私"
  pageRef = "privacy"
