# config/_default/menus.zh-Hans.toml

# -- 顶部导航菜单 --
# 定义网站顶部导航栏的内容

# 主页菜单项
[[main]]
  name = "主页"
  pageRef = "/"
  weight = 10

# 日常博客菜单项
[[main]]
  name = "日常博客"
  pageRef = "post"
  weight = 20

# AI文章菜单项
[[main]]
  name = "AI"
  pageRef = "ai"
  weight = 30
  
# 标签页面菜单项
[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 40
# 关于页面菜单项
[[main]]
  name = "关于"
  pageRef = "about"
  weight = 50

# 搜索图标菜单项
[[main]]
  identifier = "search"
  weight = 99
  # 是否显示名称（设为false只显示图标）
  showName = false
  [main.params]
    icon = "search"
    action = "search"
    endpoint = "search.json"

[[footer]]
  name = "隐私"
  pageRef = "privacy"
